services:
  # Backend (Node.js API)
  - type: web
    name: receituario-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://receituario-frontend.onrender.com

  # Frontend (React Static Site)
  - type: web
    name: receituario-frontend
    runtime: static
    rootDir: Editable-Document
    buildCommand: npm install && npm run build
    plan: free
